name: Playwright Tests in Docker

on:
  push:
    branches:
      - hw31
  pull_request:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Playwright Docker image
        run: docker build -t playwright_tests_image .

      - name: Run Playwright tests
        run: docker run --rm playwright_tests_image
